module.exports ={
    "CuteFTP Mac 3.1 " : true,
    "CuteFTP 9.3.0.3 " : true,
    "SmartFTP Client 9.0.2615.0 " : true,
    "Nutanix AOS & Prism < 5.5.5 (LTS) / < 5.8.1 (STS) " : true,
    "NICO" : true,
    "FTP Voyager 16.2.0 " : true,
    "SoftX FTP Client 3.3 " : true,
    "NICO" : true,
    "CuteFTP 5.0 " : true,
    "CuteFTP 8.3.1 " : true,
    "Core FTP 2.0 " : true,
    "FTP2FTP 1.0 " : true,
    "FTPShell Client 6.70 (Enterprise Edition) " : true,
    "Core FTP LE 2.2 " : true,
    "Ftp Server 1.32 " : true,
    "ALFTP 5.31 " : true,
    "FTPShell Server 6.80 " : true,
    "FTPShell Server 6.80 " : true,
    "FTPShell Client 6.7 " : true,
    "MikroTik 6.41.4 " : true,
    "OpenSSH < 6.6 SFTP " : true,
    "SEGGER embOS/IP FTP Server 3.22 " : true,
    "LabF nfsAxe 3.7 TFTP Client " : true,
    "PyroBatchFTP < 3.19 " : true,
    "LabF nfsAxe 3.7 FTP Client " : true,
    "Ayukov NFTP FTP Client 2.0 " : true,
    "LabF nfsAxe FTP Client 3.7 " : true,
    "Ruby < 2.2.8 / < 2.3.5 / < 2.4.2 / < 2.5.0" : true,
    "PSFTPd Windows FTP Server 10.0.4 Build 729 " : true,
    "Xlight FTP Server 3.8.8.5 " : true,
    "Ipswitch WS_FTP Professional < 12.6.0.3 " : true,
    "tnftp " : true,
    "Ayukov NFTP FTP Client < 2.0 " : true,
    "PyroBatchFTP 3.17 " : true,
    "FTP Made Easy PRO 1.2 " : true,
    "FTPGetter 5.89.0.85 " : true,
    "LabF nfsAxe 3.7 FTP Client " : true,
    "SpiceWorks 7.5 TFTP " : true,
    "FTPShell Server 6.56 " : true,
    "FTPShell Client 6.53 " : true,
    "Cerberus FTP Server 8.0.10.3 " : true,
    "Cerberus FTP Server 8.0.10.1 " : true,
    "FTP Voyager Scheduler 16.2.0 " : true,
    "FTPShell Client 6.53 " : true,
    "FTP Made Easy PRO 1.2 " : true,
    "Internet Download Accelerator 6.10.1.1527 " : true,
    "FTPShell Server 6.36 " : true,
    "Core FTP LE 2.2 " : true,
    "FTPShell Client 5.24 " : true,
    "WinaXe 7.7 FTP Client " : true,
    "Title" : true,
    "BolinTech DreamFTP Server 1.02 " : true,
    "PCMan FTP Server 2.0.7 " : true,
    "PCMan FTP Server 2.0.7 " : true,
    "PCMan FTP Server 2.0.7 " : true,
    "Freefloat FTP Server 1.0 " : true,
    "PCMan FTP Server 2.0.7 " : true,
    "WinaXe 7.7 'FTP client' " : true,
    "Freefloat FTP Server 1.0 " : true,
    "PCMan FTP Server 2.0.7 " : true,
    "Freefloat FTP Server 1.0 " : true,
    "KarjaSoft Sami FTP Server 2.0.2 " : true,
    "Freefloat FTP Server 1.0 " : true,
    "Freefloat FTP Server 1.0 " : true,
    "Freefloat FTP Server 1.0 " : true,
    "PCMan FTP Server 2.0.7 " : true,
    "Rumba FTP Client 4.x " : true,
    "freeFTPd 1.0.8 " : true,
    "Baby FTP server 1.24 " : true,
    "SmallFTPd 1.0.3 " : true,
    "JCraft/JSch Java Secure Channel 0.1.53 " : true,
    "ColoradoFTP 1.3 Prime Edition (Build 8) " : true,
    "zFTP Client 20061220 " : true,
    "TFTP Server 1.4 " : true,
    "Core FTP LE 2.2 " : true,
    "PCMan FTP Server 2.0.7 " : true,
    "FileZilla FTP Client 3.17.0.0 " : true,
    "Core FTP Server 32" : true,
    "Ipswitch WS_FTP LE 12.3 " : true,
    "i.FTP 2.21 " : true,
    "PCMan FTP Server 2.0.7 " : true,
    "PCMan FTP Server " : true,
    "TallSoft SNMP/TFTP Server 1.0.0 " : true,
    "Quick Tftp Server Pro 2.3 " : true,
    "Core FTP Server 1.2 " : true,
    "XM Easy Personal FTP Server 5.8.0 " : true,
    "FTPShell Client 5.24 " : true,
    "CesarFTP 0.99g " : true,
    "Konica Minolta FTP Utility 1.00 " : true,
    "FTPShell Client 5.24 " : true,
    "FTPShell Client 5.24 " : true,
    "Notepad++ NPPFtp Plugin 0.26.3 " : true,
    "Netwin SurgeFTP Sever 23d6 " : true,
    "BisonWare BisonFTP Server 3.5 " : true,
    "PCMan FTP Server 2.0.7 " : true,
    "FreshFTP 5.52 " : true,
    "Konica Minolta FTP Utility 1.0 " : true,
    "Konica Minolta FTP Utility 1.00 " : true,
    "Konica Minolta FTP Utility 1.0 " : true,
    "Monsta FTP 1.6.2 " : true,
    "GPON Home Router FTP G" : true,
    "SynaMan 4.0 build 1488 " : true,
    "Qmail SMTP " : true,
    "SysGauge 1.5.18 " : true,
    "Python smtplib 2.7.11 / 3.4.4 / 3.5.1 " : true,
    "Blat 2.7.6 SMTP / NNTP Mailer " : true,
    "Mock SMTP Server 1.0 " : true,
    "Exim ESMTP 4.80 " : true,
    "Postfix SMTP 4.2.x < 4.2.48 " : true,
    "iScripts AutoHoster " : true,
    "DeepOfix SMTP Server 3.3 " : true,
    "MIMEsweeper For SMTP " : true,
    "NJStar Communicator MiniSmtp " : true,
    "NJStar Communicator 3.00 " : true,
    "Lotus Domino SMTP Router & Email Server and Client " : true,
    "LeadTools Imaging LEADSmtp " : true,
    "Sitemagic CMS " : true,
    "Majordomo2 " : true,
    "Inetserv 3.23 " : true,
    "Microsoft Windows " : true,
    "AA SMTP Server 1.1 " : true,
    "SquirrelMail PGP Plugin " : true,
    "sSMTP 2.62 " : true,
    "CommuniCrypt Mail 1.16 " : true,
    "Mercury/32 Mail SMTPD " : true,
    "CommuniCrypt Mail 1.16 " : true,
    "TABS MailCarrier 2.51 " : true,
    "EasyMail Objects 'EMSMTP.DLL 6.0.1' " : true,
    "i.Scribe SMTP Client 2.00b " : true,
    "MailEnable 3.13 SMTP Service " : true,
    "Citadel SMTP 7.10 " : true,
    "QK SMTP Server " : true,
    "Postcast Server Pro 3.0.61 / Quiksoft EasyMail " : true,
    "Mercury/32 Mail Server 3.32 < 4.51 " : true,
    "Mercury/32 Mail SMTPD 4.51 " : true,
    "Mercury/32 Mail SMTPD " : true,
    "Eudora 7.1 " : true,
    "QK SMTP 3.01 " : true,
    "MailEnable 2.x " : true,
    "QK SMTP 3.01 " : true,
    "QK SMTP 3.01 " : true,
    "Hastymail 1.x " : true,
    "MailEnable 1.x " : true,
    "Apache James Server 2.2 " : true,
    "BL4 SMTP Server < 0.1.5 " : true,
    "SoftiaCom wMailServer 1.0 " : true,
    "Free SMTP Server 2.2 " : true,
    "nbSMTP 0.99 " : true,
    "Inframail Advantage Server Edition 6.0 < 6.37 " : true,
    "GoodTech SMTP Server 5.14 " : true,
    "dSMTP Mail Server 3.1b (Linux) " : true,
    "MailEnable Enterprise 1.x " : true,
    "SPECTral Personal SMTP Server 0.4.2 " : true,
    "Qwik SMTP 0.3 " : true,
    "TABS MailCarrier 2.51 " : true,
    "BaSoMail Server 1.24 " : true,
    "YahooPOPs 1.6 " : true,
    "YahooPOPs 1.6 " : true,
    "Alt" : true,
    "Alt" : true,
    "MDaemon SMTP Server 5.0.5 " : true,
    "Mailtraq 2.1.0.1302 " : true,
    "BaSoMail 1.24 " : true,
    "FloosieTek FTGate PRO 1.22 " : true,
    "FloosieTek FTGate PRO 1.22 " : true,
    "EType EServ 2.9x " : true,
    "CodeBlue 5.1 " : true,
    "Microsoft IIS 4.0/5.0 " : true,
    "Softek MailMarshal 4 / Trend Micro ScanMail 1.0 " : true,
    "MAILsweeper SMTP 4.2.1 + F" : true,
    "Cobalt Raq3 PopRelayD " : true,
    "Network Associates Webshield SMTP 4.5 " : true,
    "Cisco PIX Firewall 4.x/5.x " : true,
    "Jack De Winter WinSMTP 1.6 f/2.0 " : true,
    "Computalynx CMail 2.3 SP2/2.4 " : true,
    "NetcPlus SmartServer 3.5.1 " : true,
    "Lotus Domino 4.6.1/4.6.4 Notes " : true,
    "Alt" : true,
    "SmartMax MailMax 1.0 " : true,
    "Ipswitch Imail Server 5.0 " : true,
    "Microsoft Exchange Server 4.0/5.0 " : true,
    "Navicat 12.0.29 " : true,
    "Linux/x86 " : true,
    "libSSH " : true,
    "WirelessHART Fieldgate SWG70 3.0 " : true,
    "Eaton Xpert Meter 13.4.0.10 " : true,
    "OpenSSH 2.3 < 7.7 " : true,
    "OpenSSH 2.3 < 7.7 " : true,
    "OpenSSH < 6.6 SFTP " : true,
    "Analyze & Attack SSH Protocol" : true,
    "Trustwave SWG 11.8.0.27 " : true,
    "FLIR Thermal Camera F/FC/PT/D " : true,
    "NethServer 7.3.1611 " : true,
    "Pelco Sarix/Spectra Cameras " : true,
    "PuTTY < 0.68 " : true,
    "Tecnovision DLX Spot " : true,
    "Mercurial " : true,
    "OpenSSH 6.8 < 6.9 " : true,
    "OpenSSH < 7.4 " : true,
    "OpenSSH < 7.4 " : true,
    "OpenSSH 7.2 " : true,
    "Core FTP LE 2.2 " : true,
    "Axessh 4.2 " : true,
    "OpenSSH 7.2p2 " : true,
    "OpenSSHd 7.2p2 " : true,
    "ExaGrid " : true,
    "OpenSSH 7.2p1 " : true,
    "DropBearSSHD 2015.71 " : true,
    "Roaming Through the OpenSSH Client: CVE" : true,
    "Fortinet FortiGate 4.x < 5.0.7 " : true,
    "Huawei HG630a / HG630a" : true,
    "Git 1.9.5 " : true,
    "Sysax Multi Server 6.40 " : true,
    "freeSSHd 1.3.1 " : true,
    "Private Shell SSH Client 3.3 " : true,
    "ZOC SSH Client " : true,
    "Ceragon FibeAir IP" : true,
    "OpenSSH < 6.6 SFTP (x64) " : true,
    "Quantum DXi V1000 2.2.1 " : true,
    "Loadbalancer.org Enterprise VA 7.5.2 " : true,
    "MikroTik RouterOS " : true,
    "Sysax Multi Server 6.10 " : true,
    "freeSSHd 1.2.6 " : true,
    "Linux/x86 " : true,
    "(SSH.com Communications) SSH Tectia " : true,
    "(SSH.com Communications) SSH Tectia (SSH < 2.0" : true,
    "freeSSHd 2.1.3 " : true,
    "Symantec Messaging Gateway 9.5/9.5.1 " : true,
    "F5 BIG" : true,
    "Sysax 5.53 " : true,
    "Sysax 5.53 " : true,
    "freeSSHd " : true,
    "Mambo Component Ahsshop " : true,
    "FreeBSD OpenSSH 3.5p1 " : true,
    "Novell Netware 6.5 " : true,
    "[Italian] SSH/SSL MITM" : true,
    "freeSSHd 1.0.9 " : true,
    "ProSSHD 1.2 " : true,
    "SecureCRT 4.0 Beta 2 SSH1 " : true,
    "freeSSHd 1.2.4 " : true,
    "ProSSHD 1.2 20090726 " : true,
    "freeSSHd 1.2.1 " : true,
    "Linux/x86 " : true,
    "freeSSHd 1.2.1 " : true,
    "GoodTech SSH " : true,
    "freeSSHd 1.2.1 " : true,
    "Debian OpenSSH " : true,
    "freeSSHd 1.2.1 " : true,
    "OpenSSL 0.9.8c" : true,
    "freeSSHd 1.2.1 " : true,
    "OpenSSL 0.9.8c" : true,
    "OpenSSL 0.9.8c" : true,
    "Mambo Component Ahsshop 1.51 " : true,
    "freeSSHd 1.2 " : true,
    "Ipswitch WS_FTP Server with SSH 6.1.0.0 " : true,
    "Pragma Systems FortressSSH 5.0 " : true,
    "Portable OpenSSH 3.6.1p" : true,
    "fipsShop " : true,
    "OpenSSH 4.3 p1 " : true,
    "freeSSHd 1.0.9 " : true,
    "Dropbear / OpenSSH Server " : true,
    "Microsoft Windows XP " : true,
    "phpBB 2.0.10 " : true,
    "RSSH 2.x " : true,
    "Dropbear SSH 0.34 " : true,
    "OpenSSH/PAM 3.6.1p1 " : true,
    "OpenSSH/PAM 3.6.1p1 " : true,
    "SCPOnly 2.3/2.4 " : true,
    "SecureCRT 2.4/3.x/4.0 " : true,
    "SecureCRT 2.4/3.x/4.0 " : true,
    "OpenSSH 3.x " : true,
    "OpenSSH 3.x " : true,
    "SSH (x2) " : true,
    "OpenSSH 2.x/3.x " : true,
    "SSH2 3.0 " : true,
    "OpenSSH 2.x/3.0.1/3.0.2 " : true,
    "SSH2 3.0 " : true,
    "SSH 1.2.x " : true,
    "SSH 1.2.30 " : true,
    "glibc" : true,
    "SSH 1.2.x " : true,
    "OpenSSH 1.2 " : true,
    "SSH Communications Security SSH 1.2.27 " : true,
    "NUUO NVRMini2 3.8 " : true,
    "NETGEAR " : true,
    "Herospeed " : true,
    "Google Android " : true,
    "Sagem F@st 3304" : true,
    "Polycom HDX " : true,
    "BSD " : true,
    "FreeBSD " : true,
    "Linux BSD" : true,
    "TelnetD encrypt_keyid " : true,
    "Sagem Router Fast 3304/3464/3504 " : true,
    "ProFTPd 1.3.2 rc3 < 1.3.3b (Linux) " : true,
    "ProFTPd 1.3.2 rc3 < 1.3.3b (FreeBSD) " : true,
    "Sun Solaris Telnet " : true,
    "Solaris TelnetD " : true,
    "GoodTech Telnet Server 5.0.6 " : true,
    "Telnet" : true,
    "Windows/x86 " : true,
    "FreeBSD 7.0" : true,
    "Pragma TelnetServer 7.0.4.589 " : true,
    "CCProxy 6.2 " : true,
    "Solaris 10/11 Telnet " : true,
    "SunOS 5.10/5.11 in.TelnetD " : true,
    "Verso NetPerformer Frame Relay Access Device " : true,
    "Arescom NetDSL" : true,
    "GoodTech Telnet Server < 5.0.7 " : true,
    "Multiple Vendor Telnet Client " : true,
    "GoodTech Telnet Server < 5.0.7 " : true,
    "Linux/x86 " : true,
    "Kroum Grigorov KpyM Telnet Server 1.0 " : true,
    "GoodTech Telnet Server 4.0 " : true,
    "Jordan Windows Telnet Server 1.0/1.2 " : true,
    "Jordan Windows Telnet Server 1.0/1.2 " : true,
    "Jordan Windows Telnet Server 1.0/1.2 " : true,
    "Celestial Software AbsoluteTelnet 2.0/2.11 " : true,
    "Solaris 2.6/7/8 " : true,
    "Apple Mac OSX 10.2 " : true,
    "602Pro LAN SUITE 2002 " : true,
    "Solaris TelnetD " : true,
    "Solaris 2.x/7.0/8 / IRIX 6.5.x / OpenBSD 2.x / NetBSD 1.x / Debian 3 / HP" : true,
    "3Com SuperStack II PS Hub 40 " : true,
    "BSD " : true,
    "Microsoft Windows Server 2000 " : true,
    "Pragma Systems InterAccess TelnetD Server 4.0 " : true,
    "Beck IPC GmbH IPC@CHIP " : true,
    "Microsoft Internet Explorer 5.0.1/5.5/6.0 " : true,
    "APC WEB/SNMP Management Card (9606) Firmware 3.0 " : true,
    "Hilgraeve HyperTerminal 6.0 " : true,
    "PragmaSys TelnetServer 2000 " : true,
    "Microsoft Windows Server 2000 " : true,
    "IRIX 5.2/5.3/6.x " : true,
    "Microsoft Windows Server 2000 " : true,
    "Pragma Systems InterAccess TelnetD Server 4.0 " : true,
    "Pragma Systems InterAccess TelnetD Server 4.0 Build 4 " : true,
    "GoodTech Telnet Server NT 2.2.1 " : true,
    "Byte Fusion BFTelnet 1.1 " : true,
    "Microsoft Windows 95/98 Internet Explorer 5/Telnet " : true,
    "Microsoft Windows NT 3.5.1 SP2/3.5.1 SP3/3.5.1 SP4/3.5.1 SP5/4.0/4.0 SP1/4.0 SP2/4.0..." : true
}